RESULTS = 'results'
LEXICAL_ENTRIES = 'lexicalEntries'
SENSES = 'senses'
ENTRIES = 'entries'
DEFINITIONS = 'definitions'
SHORT_DEFINITIONS = 'short_definitions'
LANGUAGE = 'language'
PRONUNCIATIONS = 'pronunciations'
